---

- name: Set the Github API endpoint
  set_fact:
    _prometheus_github_api_url: |-
      {% if prometheus_release_tag == 'latest' %}
      https://api.github.com/repos/prometheus/prometheus/releases/latest
      {% else %}
      https://api.github.com/repos/prometheus/prometheus/releases/tags/{{ prometheus_release_tag }}
      {% endif %}

- name: Set the Github API token
  set_fact:
    _prometheus_github_api_token: "{{ lookup('env', 'GITHUB_API_TOKEN') }}"

- name: Fetch the Prometheus release information from Github
  uri:
    url: "{{ _prometheus_github_api_url }}"
    method: GET
    headers:
      Authorization: "{% if _prometheus_github_api_token %}token {{ _prometheus_github_api_token }}{% endif %}"
  register: _prometheus_github_release
  until: |
    'status' in _prometheus_github_release
      and _prometheus_github_release['status'] == 200
  retries: 5
  delay: 15

- name: Get the tag of the latest Prometheus Github release
  set_fact:
    prometheus_release_tag: "{{ _prometheus_github_release['json'] | json_query('tag_name') }}"
  when: prometheus_release_tag == "latest"

- name: Set the Github download URL for the Prometheus release
  set_fact:
    prometheus_release_url: "{{ _prometheus_github_release['json'] | json_query(_prometheus_release_asset_url_query) }}"
  vars:
    _prometheus_release_asset_url_query: "assets[?name=='{{ hostvars[inventory_hostname] | prometheus_release_build(prometheus_release_tag) }}.tar.gz'] | [0].browser_download_url"  # noqa 204
