---

- include: install-prometheus.yml
- include: configure-prometheus.yml
- include: configure-rules.yml

- name: Start and enable the Prometheus service
  service:
    name: prometheus
    state: started
    enabled: true
