---

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: reload prometheus
  service:
    name: prometheus
    state: reloaded

- name: reload systemd and restart prometheus
  command: systemctl daemon-reload
  notify: restart prometheus
  tags:
    - skip_ansible_lint
