---

# Install Prometheus from a custom release URL
prometheus_release_url: |-
  https://github.com/prometheus/prometheus/releases/download/v2.7.1/prometheus-2.7.1.linux-amd64.tar.gz

# Override the default configuration defined in vars/main.yml
prometheus_config:
  global:
    # override the scrape_interval defined in vars/main.yml
    scrape_interval: 1m
    # define the scrape_timeout
    scrape_timeout: 10s

    scrape_configs:
      # scrape prometheus metrics
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      # scrape node_exporter metrics
      - job_name: "node_exporter"
        static_configs:
          - targets: ["localhost:9100"]
