---

scenario:
  # Test the out-of-the-box installation of the latest Prometheus release
  name: prometheus-latest

driver:
  name: docker

dependency:
  name: galaxy

platforms:

  - name: prometheus-centos-7
    image: centos:7
    dockerfile: ../resources/Dockerfile.centos-systemd.j2
    command: "/usr/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: prometheus-centos-8
    image: centos:7
    dockerfile: ../resources/Dockerfile.centos-systemd.j2
    command: "/usr/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: prometheus-ubuntu-1804
    image: ubuntu:18.04
    dockerfile: ../resources/Dockerfile.debian-systemd.j2
    command: "/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  - name: prometheus-debian-10
    image: debian:10
    dockerfile: ../resources/Dockerfile.debian-systemd.j2
    command: "/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  inventory:
    host_vars:
      dockerswarm-centos-8:
        ansible_python_interpreter: "/usr/bin/python3"
  options:
    diff: True
    v: True
  lint:
    name: ansible-lint

lint:
  name: yamllint

verifier:
  name: testinfra
  options:
    vvv: True
  additional_files_or_dirs:
    - ../../resources/tests/
  lint:
    name: flake8   # Will use the rules defined in .flake8
